apiVersion: apps/v1
kind: Deployment
metadata: 
    name: frontend 
    labels:
       app: frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      name: frontend
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: mimanasi/frontend:v2
          ports:
            - containerPort: 80
